import React,{useState,useEffect,lazy,Suspense} from 'react';
const CadView=lazy(()=>import('./CadView'));
import {Pause,Play,TriangleAlert,StepForward,CheckCircle2,Package,ArrowRight,FileBox,Search,ExternalLink} from 'lucide-react';
import {api,kinds,statuses,phases,time} from './api';

export function DevicePanel({state,act}){
 const d=state.device,t=state.tasks.find(t=>t.id===d.active_task),unavailable=!!state.plc&&!state.plc.connected;
 const label=unavailable?'通信中断':d.fault?'故障':d.status==='RECOVERY_REQUIRED'?'待恢复':d.paused?'已暂停':t?'运行中':'空闲';
 return <section className="panel device"><div className="panel-head"><h2>堆垛机 SC-01</h2><span className={`status ${unavailable||d.fault?'bad':d.paused?'waiting':'good'}`}><i/>{label}</span></div><div className="axes">{[['行走 X',d.x],['升降 Y',d.y],['货叉 Z',d.z]].map(([k,v])=><div key={k}><span>{k}</span><b>{v.toFixed(2)} <small>m</small></b></div>)}</div><div className="device-details"><div><span>当前任务</span><strong>{t?.number||'—'}</strong></div><div><span>货叉载具</span><strong>{d.carrying||'空载'}</strong></div><div><span>执行步骤</span><strong>{t?phases[t.phase]:'等待任务'}</strong></div><div><span>运行模式</span><strong>S7 协议软 PLC</strong></div></div><div className="device-controls"><div className="button-row"><button className="primary" disabled={unavailable||!!d.fault} onClick={()=>act('/api/simulation/control',{action:d.paused?'resume':'pause'})}>{d.paused?<Play size={16}/>:<Pause size={16}/>} {d.paused?'恢复运行':'暂停运行'}</button><button disabled={unavailable||!d.paused||!!d.fault||d.status==='RECOVERY_REQUIRED'} onClick={()=>act('/api/simulation/control',{action:'step'})}><StepForward size={16}/>单步执行</button></div><label className="inline-label">运行速度<select disabled={unavailable} aria-label="运行速度" value={d.speed} onChange={e=>act('/api/simulation/control',{action:'speed',value:Number(e.target.value)})}>{[1,2,5,10].map(n=><option key={n} value={n}>{n}.0× {n===1?'（正常）':''}</option>)}</select></label><button disabled={unavailable} className={d.fault?'danger':'fault-button'} onClick={()=>act('/api/simulation/control',{action:d.fault?'clear_fault':'fault'})}><TriangleAlert size={17}/>{d.fault?'清除仿真故障':'注入故障'}</button>{d.status==='RECOVERY_REQUIRED'&&<p className="warning-text">载具和预留已保留。确认仿真状态后，点击恢复继续。</p>}</div></section>;
}

export function TaskTable({state,act,onNew,full=false}){
 const [filter,setFilter]=useState('ALL'),[expanded,setExpanded]=useState(null);
 const tasks=[...state.tasks].reverse().filter(t=>filter==='ALL'||(filter==='ACTIVE'?['QUEUED','RUNNING','BLOCKED','RECOVERY_REQUIRED'].includes(t.status):t.status===filter));
 return <section className="panel tasks"><div className="panel-head"><h2>运输任务 <small>{state.tasks.length}</small></h2><select aria-label="筛选任务" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">全部任务</option><option value="ACTIVE">未完成</option><option value="COMPLETED">已完成</option><option value="CANCELLED">已取消</option></select></div>{!tasks.length?<div className="empty"><Package size={38}/><div><p>{state.tasks.length?'没有符合筛选条件的任务':'暂无任务，创建第一笔入库任务'}</p><button className="primary compact" onClick={onNew}>新建任务</button></div></div>:<div className="table-scroll"><table><thead><tr><th>任务编号</th><th>类型</th><th>载具</th><th>源位置</th><th>目标位置</th><th>状态</th><th>业务回执</th><th>操作</th></tr></thead><tbody>{(full?tasks:tasks.slice(0,5)).map(t=><React.Fragment key={t.id}><tr><td><button className="text-button" onClick={()=>setExpanded(expanded===t.id?null:t.id)}>{t.number}</button></td><td>{kinds[t.kind]}</td><td>{t.load_id}</td><td>{t.source}</td><td>{t.target}</td><td><span className={`status ${t.status==='COMPLETED'?'good':t.status==='RUNNING'?'blue':['BLOCKED','RECOVERY_REQUIRED'].includes(t.status)?'bad':'waiting'}`}>{statuses[t.status]}</span></td><td>{t.integration==='ACKNOWLEDGED_SIMULATION'?'模拟已确认':t.integration==='PENDING'?'待同步':'—'}</td><td>{t.status==='QUEUED'?<button className="text-button" onClick={()=>act(`/api/tasks/${t.id}/cancel`,{})}>取消</button>:t.integration==='PENDING'?<button className="text-button" onClick={()=>act(`/api/integration/outbox/${state.outbox.find(e=>e.task_id===t.id).event_id}/ack-simulation`,{})}>模拟确认</button>:'—'}</td></tr>{expanded===t.id&&<tr><td colSpan="8"><div className="task-detail"><span>步骤：{phases[t.phase]}</span><span>创建：{time(t.created_at)}</span><span>DB2 功能码：{t.plc_function}</span><span>幂等编号：{t.request_id}</span><span>UUID：{t.id}</span></div></td></tr>}</React.Fragment>)}</tbody></table></div>}</section>;
}

export function Inventory({state,act,onSelect,selected}){
 const [query,setQuery]=useState('');
 const locations=Object.values(state.locations).filter(l=>`${l.id} ${l.load||''} ${state.loads[l.load]?.sku||''}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="inventory-top"><h2>库位与载具</h2><label className="search"><Search size={17}/><input aria-label="搜索库位或载具" placeholder="搜索库位 / 载具 / 物料" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="station-row">{Object.values(state.stations).map(p=><section className="panel station" key={p.id}><div><h3>{p.id==='IN'?'入库站台':'出库站台'} · {p.id}</h3><p>{p.load||'站台空闲'} {p.reserved?'· 任务预留':''}</p></div>{p.id==='OUT'&&<button disabled={!p.load||!!p.reserved} onClick={()=>act('/api/simulation/control',{action:'release_out'})}>确认提走<ArrowRight size={15}/></button>}</section>)}</div><section className="panel"><div className="panel-head"><h2>库位清单 <small>{locations.length}</small></h2><span className="muted">点击查看占用与预留</span></div><div className="table-scroll"><table><thead><tr><th>库位</th><th>侧 / 列 / 层</th><th>状态</th><th>载具</th><th>物料</th><th>数量</th><th>重量</th></tr></thead><tbody>{locations.map(l=>{const load=state.loads[l.load];return <tr key={l.id} className={selected===l.id?'highlight':''}><td><button className="text-button" onClick={()=>onSelect(l.id)}>{l.id}</button></td><td>{l.side==='L'?'左':'右'} / {l.column} / {l.level}</td><td><span className={`status ${l.reserved?'blue':l.load?'good':'waiting'}`}>{l.reserved?'预留':l.load?'占用':'空闲'}</span></td><td>{l.load||'—'}</td><td>{load?.sku||'—'}</td><td>{load?.quantity??'—'}</td><td>{load?`${load.weight_kg} kg`:'—'}</td></tr>})}</tbody></table></div></section></>;
}

export function Structure(){
 const [data,setData]=useState(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[showCad,setShowCad]=useState(false);
 useEffect(()=>{api('/api/structure').then(setData).catch(e=>setError(e.message));},[]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p>读取结构资料…</p>;
 return <><div className="inventory-top"><h2>结构资料</h2><span className="muted">原始文件只读保留</span></div><div className="structure-summary"><FileBox size={36}/><div><h2>{data.assembly_count} 个装配体 · {data.part_count} 个零件</h2><p>{data.note}</p>{data.mesh_report&&<p>已导出 {data.mesh_report.exported_instances} 个构件实例；{data.mesh_report.missing_components.length} 个构件缺少网格。本页查看原始装配；动态映射见运行总览。</p>}{data.cad_url&&<button className="primary compact" onClick={()=>setShowCad(!showCad)}>{showCad?"收起真实装配":"查看真实装配"}</button>}</div></div>{showCad&&<Suspense fallback={<p>加载模型查看器…</p>}><CadView url={data.cad_url}/></Suspense>}<div className="station-row">{data.previews?.map(p=><section key={p.file} className="panel cad-preview"><img src={p.url} alt={p.file}/><h3>{p.file}</h3></section>)}</div><section className="panel"><div className="panel-head"><h2>文件索引</h2><label className="search"><Search size={16}/><input aria-label="搜索结构文件" placeholder="搜索零件或装配名称" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-scroll"><table><thead><tr><th>文件名称</th><th>类型</th><th>大小</th><th>SHA-256（前 12 位）</th></tr></thead><tbody>{data.files?.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())).map(f=><tr key={f.name}><td>{f.name}</td><td>{f.type}</td><td>{(f.bytes/1024/1024).toFixed(2)} MB</td><td><code>{f.sha256.slice(0,12)}</code></td></tr>)}</tbody></table></div></section></>;
}

export function Events({events}){return <section className="panel events"><div className="panel-head"><h2>事件记录</h2><span className="muted">最近 {Math.min(events.length,8)} 条 · 持久化审计</span></div><div className="table-scroll"><table><thead><tr><th>时间</th><th>级别</th><th>事件内容</th></tr></thead><tbody>{events.slice(0,8).map(e=><tr key={e.id}><td>{time(e.time)}</td><td><span className={`event-level ${e.level}`}>{e.level==='warning'?'提示':'信息'}</span></td><td>{e.message}</td></tr>)}</tbody></table></div></section>}


