# Generated by Django 5.2.17 on 2026-08-12 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '管理操作审计',
                'verbose_name_plural': '管理操作审计',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_report_id', models.CharField(max_length=64, unique=True, verbose_name='原系统报工 ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='幂等键')),
                ('production_id', models.CharField(max_length=64, verbose_name='MO ID')),
                ('workorder_id', models.CharField(max_length=64, verbose_name='WO ID')),
                ('worker_id', models.CharField(max_length=64, verbose_name='员工 ID')),
                ('worker_name', models.CharField(max_length=128, verbose_name='员工姓名')),
                ('worker_team', models.CharField(blank=True, max_length=128, verbose_name='班组')),
                ('operation_code', models.CharField(max_length=128, verbose_name='工序代码')),
                ('operation_name', models.CharField(max_length=128, verbose_name='工序名称')),
                ('order_id', models.CharField(blank=True, max_length=128, verbose_name='订单号')),
                ('order_customer', models.CharField(blank=True, max_length=255, verbose_name='客户')),
                ('order_product', models.CharField(blank=True, max_length=255, verbose_name='产品')),
                ('quantity', models.PositiveIntegerField(verbose_name='报工数量')),
                ('qualified_quantity', models.PositiveIntegerField(default=0, verbose_name='合格数量')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工时')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('reported_at', models.DateTimeField(verbose_name='报工时间')),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('partial', '部分成功'), ('failed', '同步失败'), ('cancelled', '已作废')], default='pending', max_length=16, verbose_name='同步状态')),
                ('material_sync_status', models.CharField(blank=True, max_length=32, verbose_name='物料同步状态')),
                ('odoo_report_id', models.CharField(blank=True, max_length=64, verbose_name='Odoo 报工 ID')),
                ('odoo_stock_move_ids', models.JSONField(blank=True, default=list, verbose_name='Odoo 库存移动 ID')),
                ('odoo_progress_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Odoo 工单进度')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('voided', '已作废'), ('corrected', '已更正')], default='pending', max_length=16, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_work_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
                'permissions': [('export_workreport', 'Can export work reports'), ('review_workreport', 'Can review work reports')],
            },
        ),
        migrations.CreateModel(
            name='ReportSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('report', '报工记录'), ('material', '物料同步'), ('progress', 'WO/MO 进度')], max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_events', to='reports.workreport')),
            ],
            options={
                'verbose_name': '同步事件',
                'verbose_name_plural': '同步事件',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportMaterialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('bom_line_id', models.CharField(blank=True, max_length=64)),
                ('default_code', models.CharField(blank=True, max_length=128)),
                ('actual_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('uom_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_snapshots', to='reports.workreport')),
            ],
            options={
                'verbose_name': '物料确认快照',
                'verbose_name_plural': '物料确认快照',
            },
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['reported_at'], name='report_reported_at_idx'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['worker_id', 'reported_at'], name='report_worker_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['workorder_id', 'operation_code'], name='report_wo_operation_idx'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['sync_status'], name='report_sync_status_idx'),
        ),
    ]
