# Generated by Django 5.2.17 on 2026-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsyncevent',
            name='event_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
