# Generated by Django 5.2.17 on 2026-08-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_workreport_production_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workreport',
            options={'ordering': ['-reported_at', '-id'], 'permissions': [('export_workreport', 'Can export work reports'), ('review_workreport', 'Can review work reports')], 'verbose_name': '报工记录', 'verbose_name_plural': '报工记录'},
        ),
    ]
