# Generated by Django 5.2.17 on 2026-08-17 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_operation_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReportPanelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='登录账号')),
                ('password_hash', models.CharField(max_length=128, verbose_name='密码哈希')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_panel_account', to='employees.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '员工报工面板账号管理',
                'verbose_name_plural': '员工报工面板账号管理',
                'ordering': ('employee__department__name', 'employee__name', 'id'),
            },
        ),
    ]
