import React from 'react';
import {Check,ChevronRight,FileText,FileSpreadsheet,TriangleAlert,ArrowUpRight,Plus} from 'lucide-react';
import {Panel,Badge,Empty} from './ui';
import {files,purchases} from './data';
const stages=[['方案确认','08月10日'],['设备到场','08月28日'],['现场安装','09月05日'],['联调测试','09月15日'],['验收交付','09月18日']];
export function TaskTable({tasks,toggleTask,setModal,full=false}){return tasks.length?<div className="table-wrap"><table className="task-table"><thead><tr><th className="check-cell"><span className="checkbox-symbol"/></th><th>任务名称</th><th>负责人</th><th>截止时间</th><th>优先级</th>{full&&<th>状态</th>}<th>操作</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id} className={t.status==='已完成'?'completed':''}><td><input type="checkbox" aria-label={`完成${t.title}`} checked={t.status==='已完成'} onChange={()=>toggleTask(t.id)}/></td><td><button className="row-title" onClick={()=>setModal({type:'taskDetail',task:t})}>{t.title}</button></td><td>{t.owner}</td><td className="nowrap">{t.due}</td><td><Badge>{t.priority}</Badge></td>{full&&<td><span className={`status-dot ${t.status==='已完成'?'green':''}`}/>{t.status}</td>}<td><button className="row-more" aria-label={`查看${t.title}`} onClick={()=>setModal({type:'taskDetail',task:t})}>···</button></td></tr>)}</tbody></table></div>:<Empty/>;}
export function Overview({state,go,toggleTask,openFile,setModal}){
 const stats=[['剩余天数',9,'天','teal'],['待完成任务',state.tasks.filter(t=>t.status!=='已完成').length,'项','teal'],['阻塞问题',2,'项','red-text'],['现场人员',state.people.filter(p=>p.state==='在场').length,'人','']];
 return <><section className="stats">{stats.map(([label,value,unit,color])=><div key={label}><span>{label}</span><p><strong className={color}>{value}</strong>{unit}</p></div>)}</section><section className="milestones"><h2>交付节点</h2><div className="stage-track">{stages.map(([label,date],i)=><div key={label} className={`stage ${i<2?'done':i===2?'current':''}`}><span className="stage-circle">{i<2?<Check size={18}/>:i===2?<i/>:null}</span><strong>{label}</strong><span>{date}</span></div>)}</div></section>
 <div className="overview-grid"><Panel title="今天优先处理（4）"><TaskTable tasks={state.tasks.filter(t=>[1,2,3,4].includes(t.id))} toggleTask={toggleTask} setModal={setModal}/></Panel><section className="risk-panel"><h2><TriangleAlert size={23}/>需要协调 <span>（2）</span></h2>{[['输送线传感器到货延迟','高风险','供应商反馈传感器预计延迟 5 天到货，可能影响联调进度。','张工','确认替代型号或加急发货方案'],['二层平台安装图待确认','中风险','最新图纸尚未确认，存在安装尺寸不一致风险。','李工','与设计方确认并发放正式图纸']].map(([title,level,desc,owner,next])=><button className="risk-item" key={title} onClick={()=>setModal({type:'note',title,description:desc})}><div><h3>{title}</h3><Badge tone={level==='高风险'?'red':'orange'}>{level}</Badge></div><p>{desc}</p><p>负责人：<strong>{owner}</strong>　|　跟进：{next}</p><ChevronRight className="risk-arrow" size={18}/></button>)}</section></div>
 <div className="bottom-grid"><Panel title="项目动态" action="查看全部" onAction={()=>go('activity')}><div className="activity-list">{state.activity.slice(0,2).map((a,i)=><div className="activity-row" key={i}><span>{a.time}</span><strong>{a.text}</strong><span>{a.owner}</span></div>)}</div></Panel><Panel title="常用资料" action="查看全部" onAction={()=>go('files')}><div className="file-list">{files.slice(0,2).map(f=><button key={f.id} className="file-row" onClick={()=>openFile(f)}>{f.ext==='PDF'?<FileText className="red-text"/>:<FileSpreadsheet className="teal"/>}<strong>{f.name}{f.type==='图纸'?`_${f.version}`:''}.{f.ext.toLowerCase()}</strong><span>{f.date}</span><ChevronRight size={18}/></button>)}</div></Panel></div></>;
}
export function FilesView({search,filter,openFile}){const list=files.filter(f=>(filter==='全部'||f.type===filter)&&`${f.name}${f.owner}`.includes(search));return <Panel title="项目资料"><div className="notice">使用图纸前请核对版本和状态；待确认资料在列表中单独标记。</div>{list.length?<div className="table-wrap"><table><thead><tr><th>文件名称</th><th>版本</th><th>使用状态</th><th>维护人</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{list.map(f=><tr key={f.id}><td><button className="file-name row-title" onClick={()=>openFile(f)}><FileText className={f.ext==='PDF'?'red-text':'teal'}/>{f.name}<small>{f.ext}</small></button></td><td>{f.version}</td><td><Badge>{f.state}</Badge></td><td>{f.owner}</td><td>{f.date}</td><td><button className="text-button" onClick={()=>openFile(f)}>查看<ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>:<Empty/>}</Panel>;}
export function PurchaseView({search,filter,setModal}){const list=purchases.filter(x=>(filter==='全部'||x.status===filter)&&`${x.name}${x.owner}${x.supplier}${x.id}`.includes(search));return <Panel title="关联采购 · 示例"><div className="notice">到货信息为演示数据；跟进记录由项目单独保存。</div>{list.length?<div className="table-wrap"><table><thead><tr><th>物资 / 采购单</th><th>数量</th><th>供应商</th><th>预计到货</th><th>状态</th><th>负责人</th><th>操作</th></tr></thead><tbody>{list.map(x=><tr key={x.id}><td><strong>{x.name}</strong><div className="secondary">{x.id} · {x.spec}</div></td><td>{x.qty} {x.unit}</td><td>{x.supplier}</td><td className={x.status==='到货延迟'?'red-text':''}>{x.date}</td><td><Badge>{x.status}</Badge></td><td>{x.owner}</td><td><button className="text-button" onClick={()=>setModal({type:'note',title:`采购跟进 · ${x.name}`,description:`${x.id} / ${x.supplier} / 预计 ${x.date}到货`})}>跟进<ChevronRight size={17}/></button></td></tr>)}</tbody></table></div>:<Empty/>}</Panel>;}
export function InventoryView({state,search,filter,setModal}){const list=(filter==='出入库记录'?state.movements:state.inventory).filter(x=>x.name.includes(search));return <Panel title={filter==='出入库记录'?'现场出入库记录':'现场物资结存'}><div className="notice">现场临时仓库 · 数量仅代表项目现场结存，各类物资分别计量。</div>{!list.length?<Empty>{filter==='出入库记录'?'还没有登记记录，点击“登记出入库”试一次收料。':'没有符合条件的物资'}</Empty>:<div className="table-wrap"><table><thead><tr>{(filter==='出入库记录'?['物资','操作','数量','经手人','备注']:['物资名称','规格','现场结存','存放位置','操作']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{list.map(x=>filter==='出入库记录'?<tr key={x.id}><td><strong>{x.name}</strong></td><td><Badge>{x.kind}</Badge></td><td>{x.qty} {x.unit}</td><td>{x.person}</td><td>{x.note||'—'}</td></tr>:<tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.spec}</td><td><strong className={x.qty===0?'red-text':'teal'}>{x.qty}</strong> {x.unit}</td><td>{x.location}</td><td><button className="text-button" onClick={()=>setModal({type:'stock',item:x.id})}>登记<Plus size={17}/></button></td></tr>)}</tbody></table></div>}</Panel>;}
export function PeopleView({state,setState,search,filter,setToast}){const list=state.people.filter(x=>(filter==='全部'||x.team===filter)&&`${x.name}${x.team}`.includes(search));return <Panel title={`现场人员 · ${state.people.filter(p=>p.state==='在场').length} 人在场`}>{list.length?<div className="table-wrap"><table><thead><tr><th>姓名</th><th>班组</th><th>岗位</th><th>当前任务</th><th>现场状态</th><th>操作</th></tr></thead><tbody>{list.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.team}</td><td>{x.role}</td><td>{x.task}</td><td><Badge tone={x.state==='在场'?'green':'neutral'}>{x.state}</Badge></td><td><button className="text-button" onClick={()=>{setState(s=>({...s,people:s.people.map(p=>p.id===x.id?{...p,state:p.state==='在场'?'已离场':'在场'}:p),activity:[{time:'刚刚',text:`${x.name}${x.state==='在场'?'离场':'进场'}登记`,owner:'林远'},...s.activity]}));setToast('人员状态已更新（演示）');}}>{x.state==='在场'?'登记离场':'登记进场'}</button></td></tr>)}</tbody></table></div>:<Empty/>}</Panel>;}
export function ProjectsView({go,state}){return <Panel title="进行中的项目"><button className="project-row" onClick={()=>go('overview')}><div className="project-symbol">苏</div><div><h3>苏州立库交付</h3><p>智能仓储一期 · 现场安装</p></div><Badge tone="orange">交期临近</Badge><div><strong>09月18日</strong><p>计划交付</p></div><div><strong>{state.tasks.filter(t=>t.status!=='已完成').length} 项</strong><p>待完成任务</p></div><ChevronRight/></button></Panel>;}
