import React,{useState} from 'react';
import {api,requestId,formatTime,displayLocationText} from './api';
import {ConfirmDialog,Empty} from './components';
import DeviceSettings from './DeviceSettings';
import Pager from './Pager';
import {usePagination,useViewport} from './paging';

const statusNames={1:'出库完成',2:'入库完成',3:'调仓完成',4:'移动完成',5:'取箱完成',6:'放箱完成',7:'异常',8:'空闲',9:'忙线',10:'复位完成'};
export default function DevicePage({state,canEdit,refresh,notify}){
 const [action,setAction]=useState(null),[id,setId]=useState(''),[editingIp,setEditingIp]=useState(false),[tab,setTab]=useState('status');
 const {height,width}=useViewport();
 const paging=usePagination(state.events,width<760?Math.max(3,Math.floor((height-310)/60)):Math.max(2,Math.min(5,Math.floor((height-590)/44))));
 const plc=state.plc,values=Object.fromEntries((plc.signals||[]).map(signal=>[signal.address,signal.value]));
 function open(kind){setId(requestId());setAction({kind,task:plc.command_task_id,status:values['DB2.DBW0']});}
 const rows=[['PLC',plc.endpoint],['CPU',`${plc.cpu_model||'—'} / ${plc.cpu_state?.replace('S7CpuStatus','')}`],['采样状态',`${plc.live?'实时':'未更新'} · ${formatTime(plc.updated_at)}`],['设备状态',`${statusNames[values['DB2.DBW0']]||'—'} (${values['DB2.DBW0']??'—'})`],['报警代码',values['DB2.DBW4']??'—'],['远程任务许可',values['DB2.DBW6']===1?'允许接单':'未开启'],['已完成任务号',values['DB2.DBW2']??'—'],['命令任务号 / 命令码',`${plc.command_task_id??'—'} / ${plc.command_code??'—'}`],['完成确认位',plc.idle_ack??'—'],['后台读写',state.write_enabled?'读取 / 写入已启用':'只读']];
 return <div className="wm-device-page" data-tab={tab}><div className="wm-tabs wm-device-mobile-tabs"><button className={tab==='status'?'selected':''} onClick={()=>setTab('status')}>设备状态</button><button className={tab==='events'?'selected':''} onClick={()=>setTab('events')}>操作记录</button></div><div className="wm-device-grid"><section className="wm-panel"><div className="wm-panel-title"><h2>真机连接</h2><button disabled={!canEdit||!state.device_settings?.editable} onClick={()=>setEditingIp(true)}>修改 IP</button></div><dl className="wm-info-list wm-device-info">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
  <section className="wm-panel wm-device-readiness"><h2>任务接单条件</h2>{state.readiness.ready?<p className="wm-success">PLC 已具备接单条件，可在任务页核对下发。</p>:<ul className="wm-readiness">{state.readiness.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}{plc.last_error&&<p className="wm-error">{plc.last_error}</p>}<p className="wm-help">现场 HMI 需处于远程模式并允许任务执行。后台不会替代 PLC 的联锁判断。</p><div className="wm-device-actions"><button disabled={!canEdit||!plc.live||values['DB2.DBW6']!==1||!([1,2,3,4,5,6,8].includes(values['DB2.DBW0']))} onClick={()=>open('ack')}>确认外部完成回执</button><button className="wm-danger" disabled={!canEdit||!plc.live} onClick={()=>open('stop')}>请求任务停止</button></div><p className="wm-help">任务停止是 PLC 软件指令；现场急停请使用设备实体急停。</p><div className="wm-axis-section"><h3>轴位置</h3><dl className="wm-axis-strip">{(plc.axes||[]).map(axis=><div key={axis.axis}><dt>{axis.name}</dt><dd>{axis.value.toFixed(3)} <small>mm{!plc.axis_live&&' · 上次采样'}</small></dd></div>)}</dl>{!plc.axes?.length&&<p className="wm-help">暂无轴位置采样</p>}</div></section></div>
  <section className="wm-panel wm-events wm-data-panel"><div className="wm-panel-title"><h2>操作记录</h2><span className="wm-help">{state.events.length} 条</span></div><div className="wm-table-wrap"><table><colgroup><col style={{width:'24%'}}/><col/></colgroup><thead><tr><th>时间</th><th>记录</th></tr></thead><tbody>{paging.items.map(event=><tr key={event.id}><td>{formatTime(event.time)}</td><td>{displayLocationText(event.message)}</td></tr>)}</tbody></table></div>{!state.events.length&&<Empty title="暂无操作记录"/>}<Pager paging={paging} label="操作记录"/></section>
  {editingIp&&state.device_settings&&<DeviceSettings settings={state.device_settings} canEdit={canEdit} onClose={()=>setEditingIp(false)} onDone={async changed=>{await refresh();notify(changed?'设备 IP 已保存，正在重新连接，请查看采样状态':'设备 IP 未变化');}}/>}
  {action&&<ConfirmDialog title={action.kind==='stop'?'向 PLC 请求任务停止':'确认外部任务完成回执'} danger={action.kind==='stop'} label={action.kind==='stop'?'已核对现场控制权，确认发送软件停止请求':'已核对外部任务完成，确认复归空闲；不改变 WMS 库存'} button={action.kind==='stop'?'发送停止请求':'确认回执'} onClose={()=>setAction(null)} onConfirm={async()=>{if(action.kind==='stop')await api('/api/device/stop',{request_id:id,site_ready:true});else await api('/api/device/acknowledge',{expected_task_id:action.task,expected_status:action.status,site_ready:true});await refresh();notify('PLC 操作已处理，请核对最新反馈');}}><p className="wm-review">PLC：{plc.endpoint}<br/>命令任务号：{action.task} · 状态：{action.status}</p></ConfirmDialog>}
 </div>;
}
