import React,{useState} from 'react';
import {api,requestId,formatTime,displayLocationText} from './api';
import {ConfirmDialog} from './components';
import DeviceSettings from './DeviceSettings';

const statusNames={1:'出库完成',2:'入库完成',3:'调仓完成',4:'移动完成',5:'取箱完成',6:'放箱完成',7:'异常',8:'空闲',9:'忙线',10:'复位完成'};
export default function DevicePage({state,canEdit,refresh,notify}){
 const [action,setAction]=useState(null),[id,setId]=useState('');
 const [editingIp,setEditingIp]=useState(false);
 const plc=state.plc,values=Object.fromEntries((plc.signals||[]).map(signal=>[signal.address,signal.value]));
 function open(kind){setId(requestId());setAction({kind,task:plc.command_task_id,status:values['DB2.DBW0']});}
 return <><div className="wm-device-grid"><section className="wm-panel"><div className="wm-panel-title"><h2>真机连接</h2><button disabled={!canEdit||!state.device_settings?.editable} onClick={()=>setEditingIp(true)}>修改 IP</button></div><dl className="wm-info-list"><div><dt>PLC</dt><dd>{plc.endpoint}</dd></div><div><dt>CPU</dt><dd>{plc.cpu_model||'—'} / {plc.cpu_state?.replace('S7CpuStatus','')}</dd></div><div><dt>采样状态</dt><dd>{plc.live?'实时':'未更新'} · {formatTime(plc.updated_at)}</dd></div><div><dt>设备状态</dt><dd>{statusNames[values['DB2.DBW0']]||'—'} ({values['DB2.DBW0']??'—'})</dd></div><div><dt>报警代码</dt><dd>{values['DB2.DBW4']??'—'}</dd></div><div><dt>远程任务许可</dt><dd>{values['DB2.DBW6']===1?'允许接单':'未开启'}</dd></div><div><dt>已完成任务号</dt><dd>{values['DB2.DBW2']??'—'}</dd></div><div><dt>命令任务号 / 命令码</dt><dd>{plc.command_task_id??'—'} / {plc.command_code??'—'}</dd></div><div><dt>完成确认位</dt><dd>{plc.idle_ack??'—'}</dd></div><div><dt>后台读写</dt><dd>{state.write_enabled?'读取 / 写入已启用':'只读'}</dd></div></dl></section><section className="wm-panel"><h2>任务接单条件</h2>{state.readiness.ready?<p className="wm-success">PLC 已具备接单条件，可在任务页核对下发。</p>:<ul className="wm-readiness">{state.readiness.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}{plc.last_error&&<p className="wm-error">{plc.last_error}</p>}<p className="wm-help">现场 HMI 需处于远程模式并允许任务执行。后台不会替代 PLC 的联锁判断。</p><div className="wm-device-actions"><button disabled={!canEdit||!plc.live||values['DB2.DBW6']!==1||!([1,2,3,4,5,6,8].includes(values['DB2.DBW0']))} onClick={()=>open('ack')}>确认外部完成回执</button><button className="wm-danger" disabled={!canEdit||!plc.live} onClick={()=>open('stop')}>请求任务停止</button></div><p className="wm-help">任务停止是 PLC 软件指令；现场急停请使用设备实体急停。</p><h3>轴位置</h3><dl className="wm-info-list">{(plc.axes||[]).map(axis=><div key={axis.axis}><dt>{axis.name}</dt><dd>{axis.value.toFixed(3)} mm{!plc.axis_live&&' · 上次采样'}</dd></div>)}</dl></section></div><section className="wm-panel wm-events"><h2>操作记录</h2><div className="wm-table-wrap"><table><thead><tr><th>时间</th><th>记录</th></tr></thead><tbody>{state.events.map(event=><tr key={event.id}><td>{formatTime(event.time)}</td><td>{displayLocationText(event.message)}</td></tr>)}</tbody></table></div></section>
 {editingIp&&state.device_settings&&<DeviceSettings settings={state.device_settings} canEdit={canEdit} onClose={()=>setEditingIp(false)} onDone={async changed=>{await refresh();notify(changed?'设备 IP 已保存，正在重新连接，请查看采样状态':'设备 IP 未变化');}}/>}
 {action&&<ConfirmDialog title={action.kind==='stop'?'向 PLC 请求任务停止':'确认外部任务完成回执'} danger={action.kind==='stop'} label={action.kind==='stop'?'已核对现场控制权，确认发送软件停止请求':'已核对外部任务完成，确认复归空闲；不改变 WMS 库存'} button={action.kind==='stop'?'发送停止请求':'确认回执'} onClose={()=>setAction(null)} onConfirm={async()=>{if(action.kind==='stop')await api('/api/device/stop',{request_id:id,site_ready:true});else await api('/api/device/acknowledge',{expected_task_id:action.task,expected_status:action.status,site_ready:true});await refresh();notify('PLC 操作已处理，请核对最新反馈');}}><p className="wm-review">PLC：{plc.endpoint}<br/>命令任务号：{action.task} · 状态：{action.status}</p></ConfirmDialog>}
 </>;
}
